version: '2'
services:
  rstudio:
    build:
      context: .
      dockerfile: Dockerfile_rstudio
    container_name: demo_rstudio
    volumes:
      - .:/home/rstudio
    ports:
      - 8787:8787
    links:
      - api
  api:
    build:
      context: .
      dockerfile: Dockerfile_API
    container_name: demo_API
    ports:
      - 8000:8000
